//
//  ETSummonerTest.h
//  XIBConverter
//
//  Created by chaoran on 16/5/17.
//  Copyright © 2016年 chaoran. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface ETSummonerTest : NSObject

+(void)testCallCFunctions;


+(void)testMsgSend;

+(void)testAutoGeneratedJS;

@end
